# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('suhdood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hashed_url', models.CharField(max_length=500)),
                ('url_string', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Url',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='display_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
