# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suhdood', '0002_auto_20170116_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='shared_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_url', to='suhdood.Url', verbose_name='URL'),
        ),
    ]
